import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {parseCsv,profileDataset,executePlan,validatePlan,inferType} from '../src/engine.js';import {canonicalPlan,comparisonPlan} from '../src/canonical.js';import {canonicalSemantics} from '../src/semantics.js';import {createProvingIntentProvider,InterpretationStatus,resolveClarification} from '../src/intent.js';
const rows=parseCsv(fs.readFileSync(new URL('../public/orders.csv',import.meta.url),'utf8'));const profile=profileDataset(rows);
test('profiles canonical data conservatively',()=>{assert.equal(profile.rowCount,13);assert.equal(profile.columns.find(c=>c.name==='order_id').type,'string');assert.equal(profile.columns.find(c=>c.name==='order_date').type,'date');assert.equal(profile.columns.find(c=>c.name==='net_revenue').nullCount,1);assert.equal(inferType('code',['001','002']),'number');assert.equal(inferType('customer_id',['001','002']),'string');});
test('computes exact monthly revenue by region excluding cancelled',()=>{const out=executePlan(rows,canonicalPlan,profile,canonicalSemantics);assert.deepEqual(out.rows,[{order_date_month:'2023-01',region:'North',sum_net_revenue:400},{order_date_month:'2023-02',region:'South',sum_net_revenue:250},{order_date_month:'2023-03',region:'West',sum_net_revenue:300},{order_date_month:'2024-01',region:'North',sum_net_revenue:450},{order_date_month:'2024-01',region:'South',sum_net_revenue:200},{order_date_month:'2024-02',region:'North',sum_net_revenue:270},{order_date_month:'2024-02',region:'West',sum_net_revenue:80},{order_date_month:'2024-02',region:'South',sum_net_revenue:0},{order_date_month:'2024-03',region:'West',sum_net_revenue:500},{order_date_month:'2024-03',region:'North',sum_net_revenue:100},{order_date_month:'2024-03',region:'South',sum_net_revenue:null}]);assert.equal(out.evidence.filteredRows,12);});
test('ranks the latest top three and compares exact prior-year values',()=>{const out=executePlan(rows,comparisonPlan,profile,canonicalSemantics);assert.deepEqual(out.rows,[{order_date_year:'2024',region:'North',sum_net_revenue:820,previous_period:'2023',previous_sum_net_revenue:400,change_sum_net_revenue:420,percent_change_sum_net_revenue:1.05},{order_date_year:'2024',region:'West',sum_net_revenue:580,previous_period:'2023',previous_sum_net_revenue:300,change_sum_net_revenue:280,percent_change_sum_net_revenue:280/300},{order_date_year:'2024',region:'South',sum_net_revenue:200,previous_period:'2023',previous_sum_net_revenue:250,change_sum_net_revenue:-50,percent_change_sum_net_revenue:-0.2}]);assert.deepEqual(out.evidence.comparison,{latestPeriod:'2024',previousPeriod:'2023',ranking:comparisonPlan.ranking});});
test('invalid plans fail before execution',()=>{const bad={...canonicalPlan,metrics:[{field:'region',aggregation:'sum'}]};assert.equal(validatePlan(bad,profile,canonicalSemantics).valid,false);assert.throws(()=>executePlan(rows,bad,profile,canonicalSemantics),/numeric field/);});
test('validates the complete versioned plan boundary without throwing',()=>{for(const [change,message] of [[{version:2},/version/],[{filters:null},/filters must be an array/],[{dimensions:[]},/dimension/],[{metrics:[]},/metric/],[{sort:[{field:'raw_secret',direction:'sideways'}]},/Sort field/],[{limit:0},/positive safe integer/],[{visualization:{type:'pie'}},/visualization/]]){const candidate={...canonicalPlan,...change};const validation=validatePlan(candidate,profile,canonicalSemantics);assert.equal(validation.valid,false);assert.match(validation.errors.join(' '),message);assert.throws(()=>executePlan(rows,candidate,profile,canonicalSemantics));}assert.deepEqual(validatePlan(null,profile,canonicalSemantics),{valid:false,errors:['Plan must be an object.']});});
test('rejects ambiguous ranking and comparison semantics',()=>{for(const [change,message] of [[{ranking:{dimension:'region',by:'sum_net_revenue',limit:0,period:'latest'}},/ranking.limit/],[{comparison:{periodDimension:'order_date_month',offset:'previous_year'}},/year-bucketed/],[{ranking:{...comparisonPlan.ranking,period:'all'}},/ranking period/]]){const candidate={...comparisonPlan,...change};const validation=validatePlan(candidate,profile,canonicalSemantics);assert.equal(validation.valid,false);assert.match(validation.errors.join(' '),message);}});
test('sums source decimals with fixed-point arithmetic',()=>{const decimalRows=parseCsv('order_id,order_date,region,net_revenue,status\n1,2024-01-01,North,0.1,completed\n2,2024-01-02,North,0.2,completed');const decimalProfile=profileDataset(decimalRows);const plan={version:1,source:'orders',filters:[{field:'status',operator:'neq',value:'cancelled'}],dimensions:[{field:'order_date',bucket:'year'},{field:'region'}],metrics:[{semanticId:'orders.net_revenue',field:'net_revenue',aggregation:'sum'}],visualization:{type:'table'}};const output=executePlan(decimalRows,plan,decimalProfile,canonicalSemantics);assert.equal(output.rows[0].sum_net_revenue,0.3);assert.match(output.evidence.arithmetic,/fixed-point/);});
test('rejects malformed CSV',()=>assert.throws(()=>parseCsv('a,b\n1'),/expected 2/));

test('declares canonical net revenue semantics without inventing currency',()=>{const metric=canonicalSemantics.metrics[0];assert.deepEqual(metric,{id:'orders.net_revenue',version:1,label:'Net revenue',sourceField:'net_revenue',aggregation:'sum',timeField:'order_date',nullPolicy:'exclude_null_values_and_report',statusPolicy:{field:'status',exclude:['cancelled'],includeOtherStatuses:true},unit:{kind:'currency',currency:'unknown'},qualifications:['Currency is not declared by the source.','Refunded rows are included because the canonical proving policy excludes only cancelled rows.']});const output=executePlan(rows,canonicalPlan,profile,canonicalSemantics);assert.equal(output.evidence.semantics[0].unit.currency,'unknown');assert.match(output.evidence.warnings.join(' '),/Refunded rows are included/);});
test('ambiguous follow-up cannot execute before clarification',()=>{const provider=createProvingIntentProvider();const interpretation=provider.propose({question:'Show the top three regions by net revenue and compare them with the previous year.',profile,semantics:canonicalSemantics,previousRevision:{number:1}});assert.equal(interpretation.status,InterpretationStatus.NEEDS_CLARIFICATION);assert.equal(interpretation.candidate,undefined);assert.equal(interpretation.ambiguities[0].choices.length,3);assert.throws(()=>executePlan(rows,interpretation.candidate?.plan,profile,canonicalSemantics));const resolved=resolveClarification(interpretation,'comparison_grain','annual_totals');assert.equal(resolved.status,InterpretationStatus.QUALIFIED);assert.equal(executePlan(rows,resolved.candidate.plan,profile,canonicalSemantics).rows.length,3);assert.throws(()=>resolveClarification(interpretation,'comparison_grain','monthly_yoy'),/not yet supported/);});
test('semantic conflicts fail before computation',()=>{const wrongCurrencyPolicy={...canonicalSemantics,metrics:[{...canonicalSemantics.metrics[0],sourceField:'gross_revenue'}]};const validation=validatePlan(canonicalPlan,profile,wrongCurrencyPolicy);assert.equal(validation.valid,false);assert.match(validation.errors.join(' '),/conflicts with semantic/);});
