import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseCsv,profileDataset} from '../src/engine.js';
import {canonicalPlan,comparisonPlan} from '../src/canonical.js';
import {canonicalSemantics} from '../src/semantics.js';
import {compileIntentProposal,createModelIntentProvider,interpretCandidate,InterpretationStatus,resolveClarification} from '../src/intent.js';
import {onRequestPost,onRequest} from '../functions/api/intent.js';

const rows=parseCsv(fs.readFileSync(new URL('../public/orders.csv',import.meta.url),'utf8')),profile=profileDataset(rows);
const provider={id:'cloudflare-workers-ai',version:'1',model:'test-model',promptVersion:'test-prompt'};
class BudgetDb{constructor(count=0){this.count=count;}prepare(sql){return {bind:()=>({run:async()=>{if(sql.startsWith('INSERT'))this.count++;},first:async()=>({request_count:this.count})})};}}

test('validated model candidate resolves without carrying model numbers',()=>{const result=interpretCandidate({question:'Show monthly net revenue by region, excluding cancelled orders.',profile,semantics:canonicalSemantics,candidate:{plan:canonicalPlan},provider});assert.equal(result.status,InterpretationStatus.RESOLVED);assert.deepEqual(result.candidate.plan,canonicalPlan);assert.equal(JSON.stringify(result).includes('resultRows'),false);});
test('bounded intent slots compile deterministically to canonical plans',()=>{assert.deepEqual(compileIntentProposal({metricId:'orders.net_revenue',timeGrain:'month',groupBy:['region'],statusPolicy:'declared',comparison:'none',ranking:'none',visualization:'line'},profile,canonicalSemantics),canonicalPlan);assert.deepEqual(compileIntentProposal({metricId:'orders.net_revenue',timeGrain:'year',groupBy:['region'],statusPolicy:'declared',comparison:'previous_year',ranking:'top_3_latest',visualization:'bar'},profile,canonicalSemantics),comparisonPlan);assert.throws(()=>compileIntentProposal({metricId:'orders.net_revenue',timeGrain:'month',groupBy:['region'],statusPolicy:'declared',comparison:'none',ranking:'none',visualization:'line',result:999},profile,canonicalSemantics),/unsupported fields/);});
test('untrusted candidates cannot smuggle result values or unsupported operations',()=>{for(const plan of [{...canonicalPlan,resultRows:[{sum_net_revenue:999999}]},{...canonicalPlan,metrics:[{...canonicalPlan.metrics[0],formula:'invented'}]},{...canonicalPlan,sql:'DROP TABLE orders'}]){const result=interpretCandidate({question:'question',profile,semantics:canonicalSemantics,candidate:{plan},provider});assert.equal(result.status,InterpretationStatus.NEEDS_CLARIFICATION);assert.equal(result.candidate,undefined);assert.match(result.ambiguities[0].prompt,/failed validation/);}});
test('model-proposed annual follow-up remains blocked until explicit clarification',()=>{const unresolved=interpretCandidate({question:'Top three regions compared with previous year',profile,semantics:canonicalSemantics,previousRevision:{number:1,plan:canonicalPlan},candidate:{plan:comparisonPlan},provider});assert.equal(unresolved.status,InterpretationStatus.NEEDS_CLARIFICATION);assert.equal(unresolved.candidate,undefined);const accepted=resolveClarification(unresolved,'comparison_grain','annual_totals');assert.equal(accepted.status,InterpretationStatus.QUALIFIED);assert.deepEqual(accepted.candidate.plan,comparisonPlan);});
test('browser provider sends bounded context and fails closed when endpoint fails',async()=>{let sent;const good=createModelIntentProvider({fetchImpl:async(_url,options)=>{sent=JSON.parse(options.body);return new Response(JSON.stringify({candidate:{plan:canonicalPlan},provider}),{status:200,headers:{'content-type':'application/json'}});}});assert.equal((await good.propose({question:'q',profile,semantics:canonicalSemantics})).status,InterpretationStatus.RESOLVED);assert.equal(sent.profile.columns[0].samples,undefined);for(const fetchImpl of [async()=>new Response(JSON.stringify({error:'offline'}),{status:502}),async()=>{throw new Error('network');}]){const failed=await createModelIntentProvider({fetchImpl}).propose({question:'q',profile,semantics:canonicalSemantics});assert.equal(failed.status,InterpretationStatus.NEEDS_CLARIFICATION);assert.equal(failed.ambiguities[0].id,'provider_unavailable');}});
test('intent Function passes no rows to AI and records model provenance',async()=>{let invocation;const intent={metricId:'orders.net_revenue',timeGrain:'month',groupBy:['region'],statusPolicy:'declared',comparison:'none',ranking:'none',visualization:'line'};const request=new Request('https://example.test/api/intent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:'q',profile:{rowCount:1,columns:[{name:'region',type:'string',nullCount:0}]},semantics:{version:1,metrics:[]},previousRevision:null})});const response=await onRequestPost({request,env:{DB:new BudgetDb(),AI:{run:async(...args)=>{invocation=args;return {response:JSON.stringify({intent})};}}}});assert.equal(response.status,200);const body=await response.json();assert.equal(body.provider.model,'@cf/meta/llama-3.3-70b-instruct-fp8-fast');assert.equal(body.candidate.intent.metricId,'orders.net_revenue');assert.equal(invocation[1].messages[1].content.includes('resultRows'),false);assert.equal(invocation[1].response_format.type,'json_schema');assert.equal((await onRequest()).status,405);});
test('intent Function rejects oversized or malformed context and model failure safely',async()=>{const env={DB:new BudgetDb(),AI:{run:async()=>{throw new Error('provider detail must not leak');}}};for(const [request,status] of [[new Request('https://x/api/intent',{method:'POST',headers:{'content-length':'32001'},body:'{}'}),413],[new Request('https://x/api/intent',{method:'POST',body:'{}'}),400],[new Request('https://x/api/intent',{method:'POST',body:JSON.stringify({question:'q',profile:{rowCount:1,columns:[]},semantics:{version:1,metrics:[]},previousRevision:null})}),502]]){const response=await onRequestPost({request,env});assert.equal(response.status,status);assert.equal((await response.text()).includes('provider detail'),false);}});
test('intent Function enforces the staging inference budget before calling AI',async()=>{let called=false;const request=new Request('https://x/api/intent',{method:'POST',body:JSON.stringify({question:'q',profile:{rowCount:1,columns:[]},semantics:{version:1,metrics:[]},previousRevision:null})}),response=await onRequestPost({request,env:{DB:new BudgetDb(100),AI:{run:async()=>{called=true;}}}});assert.equal(response.status,429);assert.equal(called,false);assert.equal(response.headers.get('retry-after'),'3600');});
