import {parseCsv,profileDataset,executePlan} from './engine.js';
import {canonicalPlan,comparisonPlan} from './canonical.js';

const app=document.querySelector('#app');
let state={rows:[],profile:null,result:null,name:'',revisions:[]};
app.innerHTML=`<header><a class="brand">DATAGRAPHS<span>.AI</span></a><div class="thesis">Trusted computation, from source to decision.</div><button id="loadSample" class="quiet">Load proving dataset</button></header><main><aside><div class="eyebrow">SOURCE</div><h2>Dataset</h2><label class="upload"><strong>Upload CSV</strong><span>Source stays in this browser for this proof.</span><input id="file" type="file" accept=".csv,text/csv"></label><div id="dataset" class="empty">No dataset loaded.</div></aside><section><div class="eyebrow">DATAGRAPH / RESULT</div><div id="hero"><div class="emptyHero"><h1>Answers you can inspect.</h1><p>Load the canonical orders dataset or upload a CSV to begin.</p></div></div></section><aside class="right"><div class="eyebrow">INTENT</div><h2>Ask the data</h2><textarea id="question" rows="4">Show monthly net revenue by region, excluding cancelled orders.</textarea><button id="run" disabled>Compute answer</button><p class="boundary">The question selects a constrained plan. Values are computed by the deterministic engine—not generated by AI.</p><div id="verify"></div></aside></main>`;

const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>value===null?'Unknown':`$${value.toFixed(2)}`;
function deepFreeze(value){if(value&&typeof value==='object'){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);}return value;}

function load(text,name){
  try{
    const rows=parseCsv(text),profile=profileDataset(rows);
    state={rows,profile,result:null,name,revisions:[]};
    $('#run').disabled=false;
    $('#dataset').innerHTML=`<div class="datasetName">${esc(name)}</div><div class="stat"><b>${profile.rowCount}</b> rows · <b>${profile.columns.length}</b> columns</div><div class="schema">${profile.columns.map(column=>`<div><span>${esc(column.name)}</span><em>${column.type}</em><small>${column.uniqueCount} unique${column.nullCount?` · ${column.nullCount} blank`:''}</small></div>`).join('')}</div>`;
    $('#hero').innerHTML=`<div class="emptyHero"><h1>Dataset ready.</h1><p>Review inferred structure, then compute the canonical question.</p></div>`;
    $('#verify').innerHTML='';
  }catch(error){alert(error.message);}
}

$('#file').addEventListener('change',async event=>{const file=event.target.files[0];if(file)load(await file.text(),file.name);});
$('#loadSample').addEventListener('click',async()=>load(await (await fetch('/orders.csv')).text(),'orders.csv'));
$('#run').addEventListener('click',()=>{
  const question=$('#question').value,normalized=question.toLowerCase();
  const isComparison=normalized.includes('top three')&&normalized.includes('previous year');
  const isCanonical=normalized.includes('monthly')&&normalized.includes('net revenue')&&normalized.includes('region')&&normalized.includes('cancel');
  if(!isCanonical&&!isComparison){alert('This proof recognizes the canonical question and its top-three previous-year follow-up. No guess was made.');return;}
  try{
    const plan=isComparison?comparisonPlan:canonicalPlan;
    const output=executePlan(state.rows,plan,state.profile);
    const revision=deepFreeze({number:state.revisions.length+1,question,plan:structuredClone(plan),output:structuredClone(output)});
    state.revisions=[...state.revisions,revision];state.result=output;render(output,revision);
  }catch(error){alert(error.message);}
});

function render(output,revision){
  if(output.evidence.comparison){renderComparison(output,revision);return;}
  const rows=output.rows,max=Math.max(...rows.map(row=>row.sum_net_revenue??0),1),colors={North:'#ef8354',South:'#63c7b2',West:'#7289da'};
  $('#hero').innerHTML=`<div class="resultHead"><div><div class="eyebrow">AUTHORITATIVE RESULT · REVISION ${revision.number}</div><h1>Monthly net revenue by region</h1></div><button id="verifyBtn" class="quiet">Verify calculation</button></div><div class="chart" role="img" aria-label="Bar chart of monthly net revenue by region">${rows.map(row=>`<div class="barRow"><time>${row.order_date_month}</time><span class="region">${esc(row.region)}</span><div class="track"><i style="width:${(row.sum_net_revenue??0)/max*100}%;background:${colors[row.region]||'#7289da'}"></i></div><b>${money(row.sum_net_revenue)}</b></div>`).join('')}</div><button id="followup" class="quiet followup">Revise: top three vs previous year</button><details><summary>Result table · ${rows.length} rows</summary><table><thead><tr><th>Month</th><th>Region</th><th>Net revenue</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${row.order_date_month}</td><td>${esc(row.region)}</td><td>${money(row.sum_net_revenue)}</td></tr>`).join('')}</tbody></table></details>`;
  $('#verifyBtn').onclick=()=>renderVerify(output.evidence,revision);
  $('#followup').onclick=()=>{$('#question').value='Show the top three regions by net revenue and compare them with the previous year.';$('#run').focus();};
}

function renderComparison(output,revision){
  const rows=output.rows,max=Math.max(...rows.flatMap(row=>[row.sum_net_revenue,row.previous_sum_net_revenue??0]),1);
  const percent=value=>value===null?'Unknown':`${value>=0?'+':''}${(value*100).toFixed(1)}%`;
  $('#hero').innerHTML=`<div class="resultHead"><div><div class="eyebrow">AUTHORITATIVE RESULT · REVISION ${revision.number}</div><h1>Top three regions · ${output.evidence.comparison.latestPeriod} vs ${output.evidence.comparison.previousPeriod}</h1><p class="revisionFrom">Revised from: ${esc(state.revisions.at(-2)?.question||'initial analysis')}</p></div><button id="verifyBtn" class="quiet">Verify calculation</button></div><div class="comparison" role="img" aria-label="Top three regions compared with previous year">${rows.map(row=>`<article><div><strong>${esc(row.region)}</strong><span>${percent(row.percent_change_sum_net_revenue)}</span></div><div class="compareBar"><i style="width:${row.sum_net_revenue/max*100}%"></i><b>${row.order_date_year} · ${money(row.sum_net_revenue)}</b></div><div class="compareBar previous"><i style="width:${(row.previous_sum_net_revenue??0)/max*100}%"></i><b>${row.previous_period} · ${money(row.previous_sum_net_revenue)}</b></div></article>`).join('')}</div><details><summary>Result table · ${rows.length} ranked regions</summary><table><thead><tr><th>Region</th><th>${output.evidence.comparison.latestPeriod}</th><th>${output.evidence.comparison.previousPeriod}</th><th>Change</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.region)}</td><td>${money(row.sum_net_revenue)}</td><td>${money(row.previous_sum_net_revenue)}</td><td>${percent(row.percent_change_sum_net_revenue)}</td></tr>`).join('')}</tbody></table></details>`;
  $('#verifyBtn').onclick=()=>renderVerify(output.evidence,revision);
}

function renderVerify(evidence,revision){
  const steps=evidence.comparison?'<li>Exclude rows where status = cancelled</li><li>Bucket order_date by calendar year and group by region</li><li>Sum net_revenue with base-10 fixed-point arithmetic</li><li>Rank the latest year, retain three regions, and join each to the immediately previous year</li>':'<li>Exclude rows where status = cancelled</li><li>Bucket order_date by calendar month</li><li>Group by month and region</li><li>Sum net_revenue with base-10 fixed-point arithmetic</li>';
  $('#verify').innerHTML=`<div class="verify"><div class="eyebrow">EVIDENCE · REVISION ${revision.number}</div><h2>Verify</h2><dl><dt>Question</dt><dd>${esc(revision.question)}</dd><dt>Source</dt><dd>${esc(state.name)}</dd><dt>Rows</dt><dd>${evidence.sourceRows} source → ${evidence.filteredRows} after filters → ${evidence.resultRows} result</dd><dt>Columns used</dt><dd>${evidence.columnsUsed.join(', ')}</dd><dt>Engine</dt><dd>${evidence.engineVersion}</dd><dt>Arithmetic</dt><dd>${esc(evidence.arithmetic)}</dd></dl><h3>Calculation</h3><ol>${steps}</ol>${evidence.warnings.length?`<div class="warning">${evidence.warnings.join(' ')}</div>`:''}<details><summary>Validated structured plan</summary><pre>${esc(JSON.stringify(evidence.plan,null,2))}</pre></details></div>`;
}
