import {parseCsv,profileDataset,executePlan} from './engine.js';
import {canonicalSemantics} from './semantics.js';
import {createProvingIntentProvider,InterpretationStatus,resolveClarification} from './intent.js';

const app=document.querySelector('#app');
const intentProvider=createProvingIntentProvider();
let state={rows:[],profile:null,result:null,name:'',revisions:[],pendingInterpretation:null};
app.innerHTML=`<header><a class="brand">DATAGRAPHS<span>.AI</span></a><div class="thesis">Trusted computation, from source to decision.</div><button id="loadSample" class="quiet">Load proving dataset</button></header><main><aside><div class="eyebrow">SOURCE</div><h2>Dataset</h2><label class="upload"><strong>Upload CSV</strong><span>Source stays in this browser for this proof.</span><input id="file" type="file" accept=".csv,text/csv"></label><div id="dataset" class="empty">No dataset loaded.</div></aside><section><div class="eyebrow">DATAGRAPH / RESULT</div><div id="hero"><div class="emptyHero"><h1>Answers you can inspect.</h1><p>Load the canonical orders dataset or upload a CSV to begin.</p></div></div></section><aside class="right"><div class="eyebrow">INTENT</div><h2>Ask the data</h2><textarea id="question" rows="4">Show monthly net revenue by region, excluding cancelled orders.</textarea><button id="run" disabled>Compute answer</button><p class="boundary">The question selects a constrained plan. Values are computed by the deterministic engine—not generated by AI.</p><div id="verify"></div></aside></main>`;

const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const metricValue=value=>value===null?'Unknown':value.toFixed(2);
function deepFreeze(value){if(value&&typeof value==='object'){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);}return value;}

function load(text,name){
  try{
    const rows=parseCsv(text),profile=profileDataset(rows);
    state={rows,profile,result:null,name,revisions:[],pendingInterpretation:null};
    $('#run').disabled=false;
    $('#dataset').innerHTML=`<div class="datasetName">${esc(name)}</div><div class="stat"><b>${profile.rowCount}</b> rows · <b>${profile.columns.length}</b> columns</div><div class="schema">${profile.columns.map(column=>`<div><span>${esc(column.name)}</span><em>${column.type}</em><small>${column.uniqueCount} unique${column.nullCount?` · ${column.nullCount} blank`:''}</small></div>`).join('')}</div>`;
    $('#hero').innerHTML=`<div class="emptyHero"><h1>Dataset ready.</h1><p>Review inferred structure, then compute the canonical question.</p></div>`;
    $('#verify').innerHTML='';
  }catch(error){alert(error.message);}
}

$('#file').addEventListener('change',async event=>{const file=event.target.files[0];if(file)load(await file.text(),file.name);});
$('#loadSample').addEventListener('click',async()=>load(await (await fetch('/orders.csv')).text(),'orders.csv'));
$('#run').addEventListener('click',()=>{
  const interpretation=intentProvider.propose({question:$('#question').value,profile:state.profile,semantics:canonicalSemantics,previousRevision:state.revisions.at(-1)});
  if(interpretation.status===InterpretationStatus.NEEDS_CLARIFICATION){state.pendingInterpretation=interpretation;renderClarification(interpretation);return;}
  executeInterpretation(interpretation);
});

function executeInterpretation(interpretation){
  try{
    const output=executePlan(state.rows,interpretation.candidate.plan,state.profile,canonicalSemantics);
    const revision=deepFreeze({number:state.revisions.length+1,question:interpretation.question,interpretation:structuredClone(interpretation),plan:structuredClone(interpretation.candidate.plan),output:structuredClone(output)});
    state.revisions=[...state.revisions,revision];state.pendingInterpretation=null;state.result=output;render(output,revision);
  }catch(error){alert(error.message);}
}

function renderClarification(interpretation){
  const ambiguity=interpretation.ambiguities[0];
  $('#verify').innerHTML=`<div class="clarification"><div class="eyebrow">NEEDS CLARIFICATION</div><h2>${esc(ambiguity.prompt)}</h2><p>No calculation ran. Choose an interpretation before DataGraphs creates the next plan.</p>${ambiguity.choices.map(choice=>`<button class="choice" data-choice="${choice.id}" ${choice.available?'':'disabled'}><strong>${esc(choice.label)}</strong><span>${esc(choice.description)}</span>${choice.available?'':'<em>Not supported in this proof</em>'}</button>`).join('')}</div>`;
  document.querySelectorAll('.choice:not(:disabled)').forEach(button=>button.onclick=()=>executeInterpretation(resolveClarification(interpretation,ambiguity.id,button.dataset.choice)));
}

function render(output,revision){
  if(output.evidence.comparison){renderComparison(output,revision);return;}
  const rows=output.rows,max=Math.max(...rows.map(row=>row.sum_net_revenue??0),1),colors={North:'#ef8354',South:'#63c7b2',West:'#7289da'};
  $('#hero').innerHTML=`<div class="resultHead"><div><div class="eyebrow">AUTHORITATIVE RESULT · REVISION ${revision.number}</div><h1>Monthly net revenue by region</h1><p class="unit">Currency unknown · refunded rows included by declared policy</p></div><button id="verifyBtn" class="quiet">Verify calculation</button></div><div class="chart" role="img" aria-label="Bar chart of monthly net revenue by region">${rows.map(row=>`<div class="barRow"><time>${row.order_date_month}</time><span class="region">${esc(row.region)}</span><div class="track"><i style="width:${(row.sum_net_revenue??0)/max*100}%;background:${colors[row.region]||'#7289da'}"></i></div><b>${metricValue(row.sum_net_revenue)}</b></div>`).join('')}</div><button id="followup" class="quiet followup">Revise: top three vs previous year</button><details><summary>Result table · ${rows.length} rows</summary><table><thead><tr><th>Month</th><th>Region</th><th>Net revenue (currency unknown)</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${row.order_date_month}</td><td>${esc(row.region)}</td><td>${metricValue(row.sum_net_revenue)}</td></tr>`).join('')}</tbody></table></details>`;
  $('#verifyBtn').onclick=()=>renderVerify(output.evidence,revision);
  $('#followup').onclick=()=>{$('#question').value='Show the top three regions by net revenue and compare them with the previous year.';$('#run').focus();};
}

function renderComparison(output,revision){
  const rows=output.rows,max=Math.max(...rows.flatMap(row=>[row.sum_net_revenue,row.previous_sum_net_revenue??0]),1);
  const percent=value=>value===null?'Unknown':`${value>=0?'+':''}${(value*100).toFixed(1)}%`;
  $('#hero').innerHTML=`<div class="resultHead"><div><div class="eyebrow">AUTHORITATIVE RESULT · REVISION ${revision.number}</div><h1>Top three regions · ${output.evidence.comparison.latestPeriod} vs ${output.evidence.comparison.previousPeriod}</h1><p class="revisionFrom">Revised from: ${esc(state.revisions.at(-2)?.question||'initial analysis')}</p><p class="unit">Confirmed annual-total interpretation · currency unknown · refunded rows included</p></div><button id="verifyBtn" class="quiet">Verify calculation</button></div><div class="comparison" role="img" aria-label="Top three regions compared with previous year">${rows.map(row=>`<article><div><strong>${esc(row.region)}</strong><span>${percent(row.percent_change_sum_net_revenue)}</span></div><div class="compareBar"><i style="width:${row.sum_net_revenue/max*100}%"></i><b>${row.order_date_year} · ${metricValue(row.sum_net_revenue)}</b></div><div class="compareBar previous"><i style="width:${(row.previous_sum_net_revenue??0)/max*100}%"></i><b>${row.previous_period} · ${metricValue(row.previous_sum_net_revenue)}</b></div></article>`).join('')}</div><details><summary>Result table · ${rows.length} ranked regions</summary><table><thead><tr><th>Region</th><th>${output.evidence.comparison.latestPeriod}</th><th>${output.evidence.comparison.previousPeriod}</th><th>Change</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.region)}</td><td>${metricValue(row.sum_net_revenue)}</td><td>${metricValue(row.previous_sum_net_revenue)}</td><td>${percent(row.percent_change_sum_net_revenue)}</td></tr>`).join('')}</tbody></table></details>`;
  $('#verifyBtn').onclick=()=>renderVerify(output.evidence,revision);
}

function renderVerify(evidence,revision){
  const metric=evidence.semantics[0];
  $('#verify').innerHTML=`<div class="verify"><div class="eyebrow">EVIDENCE · REVISION ${revision.number}</div><h2>Verify</h2><dl><dt>Question</dt><dd>${esc(revision.question)}</dd><dt>Interpretation</dt><dd>${revision.interpretation.status}${revision.interpretation.qualifications?.length?` · ${esc(revision.interpretation.qualifications.join(' '))}`:''}</dd><dt>Source</dt><dd>${esc(state.name)}</dd><dt>Metric semantic</dt><dd>${esc(metric.id)} v${metric.version} · ${esc(metric.label)}</dd><dt>Unit</dt><dd>${esc(metric.unit.kind)} · currency ${esc(metric.unit.currency)}</dd><dt>Status policy</dt><dd>Exclude ${esc(metric.statusPolicy.exclude.join(', '))}; include other statuses</dd><dt>Null policy</dt><dd>${esc(metric.nullPolicy)}</dd><dt>Trace</dt><dd>v${evidence.trace.version} · plan v${evidence.trace.planVersion} · engine ${esc(evidence.trace.engineVersion)}</dd></dl><h3>Executed operations</h3><ol class="trace">${evidence.trace.operations.map(renderTraceOperation).join('')}</ol>${evidence.trace.warnings.length?`<div class="warning">${esc(evidence.trace.warnings.join(' '))}</div>`:''}<details><summary>Execution trace</summary><pre>${esc(JSON.stringify(evidence.trace,null,2))}</pre></details><details><summary>Validated structured plan</summary><pre>${esc(JSON.stringify(evidence.plan,null,2))}</pre></details></div>`;
}

function renderTraceOperation(operation){
  const rowFlow=`${operation.inputRows} → ${operation.outputRows} rows`;
  if(operation.type==='filter')return `<li><strong>Filter</strong><span>${esc(operation.filters.map(filter=>`${filter.field} ${filter.operator} ${JSON.stringify(filter.value)}`).join('; ')||'No filters')} · ${rowFlow}</span></li>`;
  if(operation.type==='group')return `<li><strong>Group</strong><span>${esc(operation.dimensions.map(dimension=>dimension.bucket?`${dimension.field} by ${dimension.bucket}`:dimension.field).join(', '))} · ${rowFlow}</span></li>`;
  if(operation.type==='aggregate')return `<li><strong>Aggregate</strong><span>${esc(operation.metrics.map(metric=>`${metric.aggregation} ${metric.field} (${metric.semanticId})`).join(', '))} · ${rowFlow}</span></li>`;
  if(operation.type==='rank')return `<li><strong>Rank</strong><span>${esc(`top ${operation.ranking.limit} ${operation.ranking.dimension} by ${operation.ranking.by} for ${operation.ranking.period}`)} · ${rowFlow}</span></li>`;
  if(operation.type==='compare')return `<li><strong>Compare</strong><span>${esc(`${operation.comparison.latestPeriod} with ${operation.comparison.previousPeriod} using ${operation.comparison.offset}`)} · ${rowFlow}</span></li>`;
  if(operation.type==='sort')return `<li><strong>Sort</strong><span>${esc(operation.sort.map(sort=>`${sort.field} ${sort.direction}`).join(', '))} · ${rowFlow}</span></li>`;
  if(operation.type==='limit')return `<li><strong>Limit</strong><span>${operation.limit} · ${rowFlow}</span></li>`;
  return `<li><strong>Unknown operation</strong><span>${esc(operation.type)} · ${rowFlow}</span></li>`;
}
