/** @typedef {'string'|'number'|'date'|'boolean'|'unknown'} ColumnType */
/** @typedef {{field:string,operator:'eq'|'neq',value:string}} Filter */
/** @typedef {{source:string,filters:Filter[],dimensions:{field:string,bucket?:'month'}[],metrics:{field:string,aggregation:'sum'|'count'|'average'|'min'|'max'}[],sort?:{field:string,direction:'asc'|'desc'}[],limit?:number,visualization:{type:'line'|'bar'|'table'}} AnalysisPlan */

export function parseCsv(text) {
  const rows=[]; let row=[], field='', quote=false;
  for(let i=0;i<text.length;i++){const c=text[i], n=text[i+1]; if(c==='"'&&quote&&n==='"'){field+='"';i++;} else if(c==='"'){quote=!quote;} else if(c===','&&!quote){row.push(field);field='';} else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==''))rows.push(row);row=[];field='';} else field+=c;}
  if(field||row.length){row.push(field);rows.push(row);} if(quote) throw new Error('CSV contains an unclosed quote.'); if(rows.length<2) throw new Error('CSV must contain a header and at least one data row.');
  const headers=rows[0].map(x=>x.trim()); if(new Set(headers).size!==headers.length||headers.some(x=>!x)) throw new Error('CSV headers must be non-empty and unique.');
  return rows.slice(1).map((values,i)=>{if(values.length!==headers.length)throw new Error(`Row ${i+2} has ${values.length} values; expected ${headers.length}.`);return Object.fromEntries(headers.map((h,j)=>[h,values[j]]));});
}
const isoDate=/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])(?:T.*)?$/;
export function inferType(name, values){const nonNull=values.filter(v=>v.trim()!==''); if(!nonNull.length)return 'unknown'; if(/(^|_)id$/i.test(name))return 'string'; if(nonNull.every(v=>/^(true|false)$/i.test(v)))return 'boolean'; if(nonNull.every(v=>isoDate.test(v)&&!Number.isNaN(Date.parse(v))))return 'date'; if(nonNull.every(v=>/^-?(?:\d+|\d*\.\d+)$/.test(v)&&Number.isFinite(Number(v))))return 'number'; return 'string';}
export function profileDataset(rows){const columns=Object.keys(rows[0]||{}).map(name=>{const values=rows.map(r=>r[name]??''), type=inferType(name,values), nonNull=values.filter(v=>v.trim()!==''); const out={name,type,nullCount:values.length-nonNull.length,uniqueCount:new Set(nonNull).size,samples:[...new Set(nonNull)].slice(0,3)}; if(type==='number')Object.assign(out,{min:Math.min(...nonNull.map(Number)),max:Math.max(...nonNull.map(Number))}); if(type==='date')Object.assign(out,{min:[...nonNull].sort()[0],max:[...nonNull].sort().at(-1)}); return out;}); return {rowCount:rows.length,columns,warnings:columns.filter(c=>c.nullCount>0).map(c=>`${c.name} contains ${c.nullCount} blank value(s).`)};}
export function validatePlan(plan, profile){const errors=[]; if(plan.source!=='orders')errors.push(`Unknown source: ${plan.source}`); const types=Object.fromEntries(profile.columns.map(c=>[c.name,c.type])); for(const item of [...plan.filters,...plan.dimensions,...plan.metrics])if(!(item.field in types))errors.push(`Unknown field: ${item.field}`); for(const m of plan.metrics)if(m.aggregation!=='count'&&types[m.field]!=='number')errors.push(`${m.aggregation} requires a numeric field: ${m.field}`); for(const d of plan.dimensions)if(d.bucket&&types[d.field]!=='date')errors.push(`Date bucketing requires a date field: ${d.field}`); return {valid:errors.length===0,errors};}
function dimensionValue(row,d){const value=row[d.field]; return d.bucket==='month'?value.slice(0,7):value;}
export function executePlan(rows,plan,profile){const validation=validatePlan(plan,profile);if(!validation.valid)throw new Error(validation.errors.join(' ')); const filtered=rows.filter(r=>plan.filters.every(f=>f.operator==='eq'?r[f.field]===f.value:r[f.field]!==f.value)); const groups=new Map(); for(const row of filtered){const dims=plan.dimensions.map(d=>dimensionValue(row,d));const key=JSON.stringify(dims);if(!groups.has(key))groups.set(key,{dims,rows:[]});groups.get(key).rows.push(row);} let result=[...groups.values()].map(g=>{const out=Object.fromEntries(plan.dimensions.map((d,i)=>[d.bucket?`${d.field}_${d.bucket}`:d.field,g.dims[i]]));for(const m of plan.metrics){const vals=g.rows.map(r=>Number(r[m.field])).filter(Number.isFinite);const key=`${m.aggregation}_${m.field}`;out[key]=m.aggregation==='count'?g.rows.length:m.aggregation==='sum'?vals.reduce((a,b)=>a+b,0):m.aggregation==='average'?(vals.reduce((a,b)=>a+b,0)/vals.length):m.aggregation==='min'?Math.min(...vals):Math.max(...vals);}return out;}); for(const s of [...(plan.sort||[])].reverse())result.sort((a,b)=>(a[s.field]>b[s.field]?1:a[s.field]<b[s.field]?-1:0)*(s.direction==='asc'?1:-1));if(plan.limit)result=result.slice(0,plan.limit);return {rows:result,evidence:{source:plan.source,sourceRows:rows.length,filteredRows:filtered.length,resultRows:result.length,columnsUsed:[...new Set([...plan.filters,...plan.dimensions,...plan.metrics].map(x=>x.field))],plan,engineVersion:'0.1.0',warnings:profile.warnings}};}
